# Generated by Django 3.1 on 2020-08-25 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140, verbose_name='問題')),
                ('answer', models.CharField(max_length=140, verbose_name='解答')),
                ('studied_at', models.DateField(verbose_name='学習日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(verbose_name='正答')),
                ('reviewed_at', models.DateField(verbose_name='復習日')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assistant.register', verbose_name='復習対象')),
            ],
            options={
                'verbose_name_plural': 'Review_Record',
            },
        ),
    ]
